#!/usr/bin/python
import time
class maquinaRaiz(object):
   'Common base class for all employees'
   ordCount = 0



   def __init__(self, rampa, sentido):
      
      self.rampa = rampa
      self.sentido = sentido

      forAction.ordCount += 1
   
   def rampaMotor1 (self) : 
      rampaLen = len(self.rampa )
      pwm = 0
      delay = 0
      for x in xrange(0,rampaLen):

          #encendido de luz 1
          if x == 0 : 
              board.digital[8].write(1)
          #apagado de luz 1 con delay
              
          elif x == (rampaLen - 1) :
              time.sleep(self.rampa [rampaLen-1] + 0.2)
              board.digital[8].write(0)

          if x%2 == 0 :
              pwm = self.rampa [x]
              pin5.write(pwm)
              
          elif x%2 == 1 :
              time.sleep(self.rampa [x])
              delay = self.rampa [x]
          print "|MAQUINA TIERRA| pwm = ", pwm, "time = ", delay

          # encendido de luz 2

   def maquinaRaices(self, sentido):

      if self.sentido in ['izq'] :
          board.digital[6].write(1)
          board.digital[7].write(0)
      elif self.sentido in ['der'] : 
          board.digital[6].write(0)
          board.digital[7].write(1)   

      elif self.sentido in ['parar'] :
          pin5.write(0)
          board.digital[6].write(0)
          board.digital[7].write(0)
          board.digital[8].write(0)   


class maquinaAgua(object):

   'Common base class for all employees'
   ordCount = 0



   def __init__(self, rampa, sentido):
      
      self.rampa = rampa
      self.sentido = sentido

      forAction.ordCount += 1


   def rampaMotor2 (rampa_) : 
      rampaLen = len(rampa_)
      pwm = 0
      delay = 0
      for x in xrange(0,rampaLen):
          
          #encendido de luz 2
          if x == 0 :
              board.digital[12].write(1)

          #apagado de luz 2 con delay
          elif x == (rampaLen - 1) :
              time.sleep(rampa_[rampaLen-1] + 0.2)
              board.digital[12].write(0)

          if x%2 == 0 :
              pwm = rampa_[x]
              pin9.write(pwm)
              
          elif x%2 == 1 :
              time.sleep(rampa_[x])
              delay = rampa_[x]
          print "|MAQUINA AGUA| pwm = ", pwm, "time = ", delay

          # encendido de luz 2



   def maquinaAgua(sentido):

      if sentido in ['izq'] :
          board.digital[10].write(1)
          board.digital[11].write(0)
      elif sentido in ['der'] : 
          board.digital[10].write(0)
          board.digital[11].write(1)  

      elif sentido in ['parar'] : 
          pin9.write(0)
          board.digital[10].write(0)
          board.digital[11].write(0)
          board.digital[12].write(0)  




