#!/usr/bin/python
import time
class forAction:
   'Common base class for all employees'
   ordCount = 0

   def __init__(self, consulta):
      self.consulta = consulta
      
      forAction.ordCount += 1
   
   def displayForAction(self):
      for x in xrange(1,10):
          print "a, a,a ,a "
          time.sleep(0.2)
      

countConsultas = 0

while True :
   pregunta = input('Digame una orden 0, 1: ')

   if pregunta != "" :
      countConsultas += 1
      

      moduCon = countConsultas%2

      print moduCon

      if moduCon%2 == 0: 
         consulta1 = forAction(pregunta)
         consulta1.displayForAction()


      if moduCon%2 == 1: 
         consulta2 = forAction(pregunta)
         consulta2.displayForAction()

   else :

      pregunta = input('Digame una orden 0, 1: ')

