#!/usr/bin/python
import time
class forAction:
   'Common base class for all employees'
   ordCount = 0

   def __init__(self, consulta):
      self.consulta = consulta
      
      forAction.ordCount += 1
   
   def displayForAction(self):
      for x in xrange(1,10):
          print "a, a,a ,a "
      

pregunta = input('Digame una orden 0, 1: ')


consulta1 = forAction(pregunta)

consulta1.displayForAction()
"""emp2.displayEmployee()
print "Total Employee %d" % Employee.empCount
"""